services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_reminder
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: xoxymesddd
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_reminder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xoxymesddd
    ports:
      - "5432:5432"
